import { makeStyles } from "@material-ui/core/styles";
export default makeStyles({
  banner: {
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center center",
    display: "block",
    height: "100%",
    width: "100%",
    margin: "0 auto",
    "-o-object-fit": "cover",
    objectFit: "cover",
    "-webkit-transition": "all .5s ease",
    transition: "all .5s ease",
    "-webkit-filter": "blur(20px)",
    filter: "blur(20px)",
    backgroundImage:
      "url('https://in.bmscdn.com/iedb/movies/images/mobile/thumbnail/large/commando-3-et00104233-04-06-2019-10-22-17.jpg')",
  },
  bannerContainer: {
    "-webkit-transition": "all .5s ease",
    transition: "all .5s ease",
    height: 300,
    position: "relative",
    overflow: "hidden",
    zIndex: 0,
  },
  overlay: {
    position: "absolute",
    zIndex: 2,
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(0,0,0,.8)",
  },
  contentWrapper: {
    width: "80%",
    margin: "auto",
    position: "relative",
    top: -201,
  },
  title: {
    color: "#fff",
    fontSize: 36,
    fontWeight: 600,
    lineHeight: 1.4,
    textShadow: "-2px 5px 10px #cccc",
  },
  language: {
    fontSize: 16,
    fontWeight: 400,
    color: "#fff",
  },
  movietype: {
    width: "11%",
    display: "inline-block",
    border: "1px solid #ddd",
    borderRadius: 20,
    textAlign: "center",
    color: "#fff",
    marginRight: 10,
    fontSize: 11,
    padding: "5px 10px",
    lineHeight: 2,
  },
  time: {
    width: "17%",
    display: "inline-block",
    color: "#fff",
    fontSize: "15px",
    lineHeight: 1.2,

    "& p": {
      width: "80%",
      top: -26,
      position: "relative",
      left: 27,
      fontSize: "14",
    },
  },
  ratingcontainer: {
    backgroundColor: "#dddddd82",
    width: "100%",
    height: 90,
    position: "relative",
    top: -323,
    zIndex: -10,
    padding: "0px 20% 0 30%",
    "& div": {
      padding: "1% 0 0 0",
    },
    "& .rating": {
      display: "inline-block",
      width: "4%",
      position: "relative",
      top: -5,
      fontSize: 20,
      marginRight: 10,
      fontWeight: 400,
      lineHeight: 1.2,
      color: "#2d181c",
    },
  },
  desc: {
    width: "41%",
    margin: "auto",
    position: "relative",
    top: -294,
  },
});
